swagger: '2.0'
info:
  version: '1.0.0'
  title: Swagger Petstore
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets/{id}:
    put:
      operationId: adPetById
      parameters:
        - name: id
          in: path
          description: ID of pet to put
          required: true
          type: string
        - name: pet
          in: body
          description: Pet to add to the store
          required: true
          schema:
            $ref: '#/definitions/pet'
      responses:
        '201':
          description: pet response
    get:
      operationId: findPetById
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: string
      responses:
        '200':
          description: pet response
          schema:
            $ref: '#/definitions/pet'
    delete:
      description: deletes a single pet based on the ID supplied
      operationId: deletePet
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          type: string
      responses:
        '204':
          description: pet deleted
definitions:
  pet:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      description:
        type: string
